version = "Two"
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Crate"
use_small_heuristics = "Max"

